version: '3.8'

services:
  vehicle-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@vehicle-db:5432/tech_challenge
      - AUTH_DATABASE_URL=postgresql+asyncpg://postgres:postgres@vehicle-db:5432/tech_challenge_auth
      - SALES_SERVICE_URL=http://sales-api:8001
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    depends_on:
      vehicle-db:
        condition: service_healthy
    restart: on-failure
    networks:
      - vehicle-network

  vehicle-db:
    image: postgres:15-alpine
    volumes:
      - vehicle_postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tech_challenge
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vehicle-network

volumes:
  vehicle_postgres_data:

networks:
  vehicle-network:
    name: vehicle-network
    driver: bridge
