apiVersion: v1
kind: Service
metadata:
  name: vehicle-management-api-service
  namespace: tech-challenge
  labels:
    app: vehicle-management-api
spec:
  type: LoadBalancer
  selector:
    app: vehicle-management-api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
